linters:
  enable:
    - revive
    - govet
    - staticcheck

issues:
  exclude-use-default: false

run:
  timeout: 5m
  tests: true
  modules:
    - ./app

linter-settings:
  govet:
    check-shadowing: true
