name: Go code quality

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: write
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install dependencies
        run: cd lambdas && cd app && go mod tidy

      - name: Run gofmt
        run: gofmt -s -w .

      - name: Commit formatted code
        run: |
          git config --global user.name 'glamboyosa'
          git config --global user.email 'ogbemudiatimothy@gmail.com'
          git pull origin ${{ github.head_ref }}
          git add .
          git commit -m "Format code with gofmt"
          git push origin HEAD:${{ github.head_ref }}

  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59
          working-directory: ./lambdas
          args: --config ./.golangci.yml
